export default {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  SIGN_UP: "SIGN_UP",
  STORE_ERROR: "STORE_ERROR",
  STORE_LOADING: "STORE_LOADING",
  GET_USER: "GET_USER",
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  CLEAR_BASKET: "CLEAR_BASKET",
  CLEAR_ERRORS: "CLEAR_ERRORS"
};
